### ISSUE TITLE
"KegCapacityLitres" not working again

### ISSUE THREAD

**Issue by DejFidOFF** [Chronolegionnaire/HydrateOrDiedrate#39]
VS 1.20.3 HD 1.7.7

have server config   "KegCapacityLitres": 200.0, and allow me storage only 100l (tapped keg)

**Comment by Chronolegionnaire** [comment]
Fixed in latest version to be released later tonight

**Comment by DejFidOFF** [comment]
> Fixed in latest version to be released later tonight

VS 1.20.4 Hydrate 1.8.5 "KegCapacityLitres" in config still not working

**Comment by Chronolegionnaire** [comment]
Out of curiosity is your server running on a Linux machine? I am not able to replicate in my dev environment

**Comment by Chronolegionnaire** [comment]
Actually linux should be irrelevant for this issue as its not related to harmony at all, not sure what could be causing this, tested in both a heavily modded scenario and with just HoD and the config option is functioning as intended in both

**Comment by DejFidOFF** [comment]
> Out of curiosity is your server running on a Linux machine? I am not able to replicate in my dev environment

No , windows GSM. This is how my config file looks like, but I can´t put more than 100l to the keg

[HydrateOrDiedrateConfig.json](https://github.com/user-attachments/files/18814275/HydrateOrDiedrateConfig.json)

**Comment by Chronolegionnaire** [comment]
Thats very strange, like I said, I am unable to replicate on my end

![Image](https://github.com/user-attachments/assets/ea438587-8ef0-48fd-b0c4-0dc9b04668da)

**Comment by DejFidOFF** [comment]
> Thats very strange, like I said, I am unable to replicate on my end
> 
> ![Image](https://github.com/user-attachments/assets/ea438587-8ef0-48fd-b0c4-0dc9b04668da)

yah it´s really strange. I try to make a new keg, take from creative.
Do you check my config?
This works:   "TunCapacityLitres": 500.0,
This not:   "KegCapacityLitres": 200.0,

**Comment by Chronolegionnaire** [comment]
Can you try deleting HoD and replacing it with the newest version just to make sure there is nothing wonky with the mods dll?

**Comment by DejFidOFF** [comment]
> Can you try deleting HoD and replacing it with the newest version just to make sure there is nothing wonky with the mods dll?

I will try this restart. But its really really anoing for me to edit the config all the time when something change.. I am running 3 servers with HoD and have no time to spend to make configs again and again and again... I want to make a config... and never ever touch that file again.. Its not rude, just feedback.

**Comment by Chronolegionnaire** [comment]
I didnt say delete the config, just the mod.

**Comment by DejFidOFF** [comment]
> I didnt say delete the config, just the mod.

ahh sorry. trying on the test server.

**Comment by DejFidOFF** [comment]
nope, not working. max capacity still just 100l. But. I fugure out, where the problem is. It´s single player config. The keg capacity take from there... so not matter whats in server config ( "KegCapacityLitres": 200.0, ) when there is single player config where is "KegCapacityLitres": 100.0, or "KegCapacityLitres": 150.0, than max capacity of the keg is 100 or 150.

**Comment by Chronolegionnaire** [comment]
I wasn't aware there is more than one config location, I use the direct vintage story api call for reading a config file api.LoadModConfig. It doesn't have any options for specifying location

**Comment by DejFidOFF** [comment]
> I wasn't aware there is more than one config location, I use the direct vintage story api call for reading a config file api.LoadModConfig. It doesn't have any options for specifying location

hmm.. a deleted config in sigle player.. log in to server. and HoD create config in single player folder. Why?  Every other configs working just fine..

**Comment by DejFidOFF** [comment]
> I wasn't aware there is more than one config location, I use the direct vintage story api call for reading a config file api.LoadModConfig. It doesn't have any options for specifying location

And why it is uses max capacity of ton from server side and nod from single side?

**Comment by Chronolegionnaire** [comment]
I double checked my code and while I did change the way configs are loaded so that it more intelligently handles missing fields in the config when I add new config options. It ultimately does the exact same call from all the previous config code I use which is just the vs api call. Theres not really anything I can do on my end to specify a config location. Maybe its an issue with vintage story 1.20.4?

**Comment by DejFidOFF** [comment]
> I double checked my code and while I did change the way configs are loaded so that it more intelligently handles missing fields in the config when I add new config options. It ultimately does the exact same call from all the previous config code I use which is just the vs api call. Theres not really anything I can do on my end to specify a config location. Maybe its an issue with vintage story 1.20.4?

Maybe. Idk I am not programmer. Just making content mods. And I am not blaming you, just reporting observations.

**Comment by Chronolegionnaire** [comment]
I did some more testing and followed this guide to setup a dedicated server using its own dedicated data path

https://wiki.vintagestory.at/Guide:Dedicated_Server

And the config is being generated and used in the correct modconfig folder in the specified data path.

I even tested by setting different config options for both single player and the server and the correct config options are used in both instances.

I'm really not sure what could be causing your issue

**Comment by Chronolegionnaire** [comment]
Were you able to find any cause for this issue (config loading from wrong location) and/or a solution? Because I am still unable to replicate the issue after very extensive testing.

**Comment by DejFidOFF** [comment]
No, It´s not just my server. I connected to COB server and AuraFury. So. Anytime you connect to the server. Some mods automaticaly make some configs in client ModConfig folder. Your HoD mod do the same. But some data takes from there - maybe your mod just takes all data from client ModConfig folder.  Maybe, just maybe your modinfo.json is missing:
  "RequiredOnClient": true,
  "RequiredOnServer": true

I am not programmer so have no idea..

**Comment by Chronolegionnaire** [comment]
I was finally able to replicate, working on a solution now

**Comment by Chronolegionnaire** [comment]
Fixed in 1.9.1. Let me know if you run into any other issues

**Comment by DejFidOFF** [comment]
Thank you so much. It wasn´t big deal.

**Comment by DejFidOFF** [comment]
It works great. Thank you.
